### ISSUE TITLE
Teaser problem when searching for "la" string

### ISSUE THREAD

**Issue by jacargentina** [fergiemcdowall/search-index-searcher#1]
In spanish, `la` is similar to `the` for female subjects.

When i search `Usando la interfaz` on my index, i get this teaser:

`Nexion Smart ERP P<span class="sc-em">la</span>tform &nbsp; » &nbsp; <span c<span class="sc-em">la</span>ss="sc-em">usando</span> <span class="sc-em">la</span> <span class="sc-em">interfaz</span> &nbsp; » &nbsp;Persiana "Inicio", "Ir a..." Persiana &quot;Inicio&quot;, &quot;Ir a...&quot; <span class="sc-em">la</span> persiana (o módulo) de Inicio facilita el acceso a los items más utilizados por el Usuario
`

I think its highlighting the `la` inside `class` from `<span class="sc-em">`

**Comment by fergiemcdowall** [comment]
Yes, search terms are highlighted by the `<span class="sc-em">` tag. This seems to be working as intended in the example you provide (or am I missing something?).

What type of behaviour are you expecting here?

**Comment by jacargentina** [comment]
Sorry, i was not clear enough.

Look at this markup (its wrong btw)

``` html
<span c<span class="sc-em">la</span>ss="sc-em">usando</span> 
```

that _should_ be just:

``` html
<span class="sc-em">usando</span> 
```

so, again, i suspect there is a _double pass_ where first one gets the markup fine, but the second pass "highlights" the c**la**ss part, right? (i mean, it breaks the previous generated html)

**Comment by fergiemcdowall** [comment]
Oh yes, I see- I was missing something! :)

Nice catch- thanks for pointing it out.

**Comment by fergiemcdowall** [comment]
In the latest (`0.8.8`) version of `search-index` the default highlighting syntax is `<b>...</b>`, and you can customise it by passing the highlighter function as `teaserHighlighter` in the query object like so: 

``` javascript
  si.search({
    query: {
      AND: [{'*': ['swiss', 'watch']}]
    },
    teaser: 'description',
    teaserHighlighter: function (string) {
      return '<booom>' + string + '</booom>'
    }
  }
```

No docs as yet, but see the tests for examples: https://github.com/fergiemcdowall/search-index/blob/master/test/node/general-tests/teaser-test.js
