### ISSUE TITLE
docVector undefined

### ISSUE THREAD

**Issue by maxime-helen-sb** [fergiemcdowall/search-index-searcher#4]
In ScoreTopScoringDocsTDIDF.js line 30, I get ```docVector``` variable undefined, and this current error in ```err``` variable:
```
[NotFoundError: Key not found in database [DOCUMENT-VECTOR￮1484077454624-1￮subna
mespaces￮]]
```

**Comment by fergiemcdowall** [comment]
Just pushed some code which _should_ fix this error

**Comment by fergiemcdowall** [comment]
(amongst other things)
